version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pradha-db
    environment:
      POSTGRES_DB: pradhadb
      POSTGRES_USER: pradha
      POSTGRES_PASSWORD: pradha123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pradha-network

  backend:
    build: ./backend-java
    container_name: pradha-backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - pradha-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://18.205.19.24:8081
    container_name: pradha-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - pradha-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pradha-network:
    driver: bridge

