server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pradha_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    enabled: true

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:pradha-main}
    base-url: ${AWS_S3_BASE_URL:https://pradha-main.s3.amazonaws.com/}
    region: ${AWS_REGION:eu-north-1}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    com.pradha.main: INFO
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
