spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pradha_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:change-this-secret-key}
      expiration: 604800000

server:
  port: 8081

cors:
  allowed-origins: "*"

aws:
  region: ${AWS_REGION:eu-north-1}
  s3:
    bucket-name: ${S3_BUCKET_NAME:pradha-main}
    base-url: ${S3_BASE_URL:https://pradha-main.s3.eu-north-1.amazonaws.com/}

