spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server.port=8081
server.address=0.0.0.0
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.main.allow-bean-definition-overriding=true
